gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - reverse
os:
  editPreset: "nvim-remote"
  edit: "pwsh -Command if (Test-Path env:NVIM) { nvim --server \"${env:NVIM}\" --remote-send q; nvim --server \"${env:NVIM}\" --remote-tab \"{{filename}}\" } else { nvim -- \"{{filename}}\" }"
  editAtLine: "pwsh -Command if (Test-Path env:NVIM) { nvim --server \"${env:NVIM}\" --remote-send q; nvim --server \"${env:NVIM}\" --remote-tab \"{{filename}}\"; nvim --server \"${env:NVIM}\" --remote-send \":{{line}}<CR>\" } else { nvim +{{line}} -- \"{{filename}}\" }"
  editAtLineAndWait: "nvim +{{line}} \"{{filename}}\""
  openDirInEditor: "pwsh -Command if (Test-Path env:NVIM) { nvim --server \"${env:NVIM}\" --remote-send q; nvim --server \"${env:NVIM}\" --remote-tab \"{{dir}}\" } else { nvim -- \"{{dir}}\" }"
